services:
  db:
    image: postgres:16-alpine
    container_name: toll_postgres
    restart: always
    environment:
      POSTGRES_DB: highway_toll
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: HighwayTollsystem/Dockerfile
    container_name: toll_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=highway_toll;Username=postgres;Password=localpassword123"

volumes:
  postgres_data: