// <auto-generated />
using System;
using HighwayTollsystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HighwayTollsystem.Migrations
{
    [DbContext(typeof(HighwayTollContext))]
    [Migration("20260727200647_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HighwayTollsystem.Models.Passage", b =>
                {
                    b.Property<long>("PassageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PassageId"));

                    b.Property<decimal>("CalculatedFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("GateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVignetteValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Spz")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleSpeed")
                        .HasColumnType("integer");

                    b.HasKey("PassageId")
                        .HasName("PK__Passages__CC0F002C4A8A415B");

                    b.HasIndex("GateId");

                    b.HasIndex(new[] { "Spz" }, "IX_Passages_Spz");

                    b.ToTable("Passages");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Stk", b =>
                {
                    b.Property<int>("StkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StkId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EmissionsValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Spz")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StkId")
                        .HasName("PK__Stk__56A80AECC8856588");

                    b.HasIndex(new[] { "Spz" }, "IX_Stk_Spz");

                    b.ToTable("Stk", (string)null);
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TollGate", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GateId"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("GpsLatitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("GpsLongitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("HighwayName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("KilometerPost")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("GateId")
                        .HasName("PK__TollGate__9582C65039CBB277");

                    b.ToTable("TollGates");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TrafficViolation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ViolationId"));

                    b.Property<decimal>("ActualPenaltyAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("PassageId")
                        .HasColumnType("bigint");

                    b.Property<int>("ViolationTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ViolationId")
                        .HasName("PK__TrafficV__18B6DC086635FFDB");

                    b.HasIndex("PassageId");

                    b.HasIndex("ViolationTypeId");

                    b.ToTable("TrafficViolations");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vehicle", b =>
                {
                    b.Property<string>("Spz")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmissionClass")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Spz")
                        .HasName("PK__Vehicles__CA1E142DEAD30959");

                    b.HasIndex("TypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BaseTarif")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TypeName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("PK__VehicleT__3214EC0735D28DED");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vignette", b =>
                {
                    b.Property<int>("VignetteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VignetteId"));

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Spz")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VignetteId")
                        .HasName("PK__Vignette__C81AEC1FA0C45C6E");

                    b.HasIndex(new[] { "Spz", "ValidFrom", "ValidTo" }, "IX_Vignettes_Spz_Dates");

                    b.ToTable("Vignettes");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.ViolationType", b =>
                {
                    b.Property<int>("ViolationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ViolationTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("DefaultPenaltyAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ViolationTypeId")
                        .HasName("PK__Violatio__3B1A4D1D71E82FAB");

                    b.HasIndex(new[] { "Code" }, "UQ__Violatio__A25C5AA7571436D1")
                        .IsUnique();

                    b.ToTable("ViolationTypes");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Passage", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.TollGate", "Gate")
                        .WithMany("Passages")
                        .HasForeignKey("GateId")
                        .IsRequired()
                        .HasConstraintName("FK__Passages__GateId__6D0D32F4");

                    b.HasOne("HighwayTollsystem.Models.Vehicle", "SpzNavigation")
                        .WithMany("Passages")
                        .HasForeignKey("Spz")
                        .IsRequired()
                        .HasConstraintName("FK__Passages__Spz__6C190EBB");

                    b.Navigation("Gate");

                    b.Navigation("SpzNavigation");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Stk", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.Vehicle", "SpzNavigation")
                        .WithMany("Stks")
                        .HasForeignKey("Spz")
                        .IsRequired()
                        .HasConstraintName("FK__Stk__Spz__693CA210");

                    b.Navigation("SpzNavigation");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TrafficViolation", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.Passage", "Passage")
                        .WithMany("TrafficViolations")
                        .HasForeignKey("PassageId")
                        .IsRequired()
                        .HasConstraintName("FK__TrafficVi__Passa__72C60C4A");

                    b.HasOne("HighwayTollsystem.Models.ViolationType", "ViolationType")
                        .WithMany("TrafficViolations")
                        .HasForeignKey("ViolationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__TrafficVi__Viola__73BA3083");

                    b.Navigation("Passage");

                    b.Navigation("ViolationType");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vehicle", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.VehicleType", "Type")
                        .WithMany("Vehicles")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Vehicles__TypeId__5FB337D6");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vignette", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.Vehicle", "SpzNavigation")
                        .WithMany("Vignettes")
                        .HasForeignKey("Spz")
                        .IsRequired()
                        .HasConstraintName("FK__Vignettes__Spz__656C112C");

                    b.Navigation("SpzNavigation");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Passage", b =>
                {
                    b.Navigation("TrafficViolations");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TollGate", b =>
                {
                    b.Navigation("Passages");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vehicle", b =>
                {
                    b.Navigation("Passages");

                    b.Navigation("Stks");

                    b.Navigation("Vignettes");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.ViolationType", b =>
                {
                    b.Navigation("TrafficViolations");
                });
#pragma warning restore 612, 618
        }
    }
}
