// <auto-generated />
using System;
using HighwayTollsystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HighwayTollsystem.Migrations
{
    [DbContext(typeof(HighwayTollContext))]
    [Migration("20260729114147_DBRebuild")]
    partial class DBRebuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HighwayTollsystem.Models.Passage", b =>
                {
                    b.Property<long>("PassageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PassageId"));

                    b.Property<decimal>("CalculatedFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("GateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<int>("VehicleSpeed")
                        .HasColumnType("integer");

                    b.HasKey("PassageId");

                    b.HasIndex("GateId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Passages");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TollGate", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GateId"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("GpsLatitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("GpsLongitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("HighwayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("KilometerPost")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("GateId");

                    b.ToTable("TollGates");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TrafficViolation", b =>
                {
                    b.Property<long>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ViolationId"));

                    b.Property<decimal>("ActualPenaltyAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("PassageId")
                        .HasColumnType("bigint");

                    b.Property<int>("ViolationType")
                        .HasColumnType("integer");

                    b.HasKey("ViolationId");

                    b.HasIndex("PassageId");

                    b.ToTable("TrafficViolations");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vehicle", b =>
                {
                    b.Property<long>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VehicleId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("CZ");

                    b.Property<int>("EmissionClass")
                        .HasColumnType("integer");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Spz")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("VehicleId");

                    b.HasIndex("Spz", "CountryCode")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.VehicleInspection", b =>
                {
                    b.Property<long>("VehicleInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VehicleInspectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EmissionsValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("VehicleInspectionId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleInspections");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vignette", b =>
                {
                    b.Property<long>("VignetteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VignetteId"));

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("VignetteId");

                    b.HasIndex("VehicleId", "ValidFrom", "ValidTo");

                    b.ToTable("Vignettes");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Passage", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.TollGate", "Gate")
                        .WithMany("Passages")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighwayTollsystem.Models.Vehicle", "Vehicle")
                        .WithMany("Passages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gate");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TrafficViolation", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.Passage", "Passage")
                        .WithMany("TrafficViolations")
                        .HasForeignKey("PassageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passage");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.VehicleInspection", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleInspections")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vignette", b =>
                {
                    b.HasOne("HighwayTollsystem.Models.Vehicle", "Vehicle")
                        .WithMany("Vignettes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Passage", b =>
                {
                    b.Navigation("TrafficViolations");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.TollGate", b =>
                {
                    b.Navigation("Passages");
                });

            modelBuilder.Entity("HighwayTollsystem.Models.Vehicle", b =>
                {
                    b.Navigation("Passages");

                    b.Navigation("VehicleInspections");

                    b.Navigation("Vignettes");
                });
#pragma warning restore 612, 618
        }
    }
}
