name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  testing-and-building:
    runs-on: ubuntu-latest

    steps:
      - name: Download repositary
        uses: actions/checkout@v4

      - name: dotNET setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Nuget install
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal